#!/bin/bash

global=/usr/bin/global_
flag=0
args=()

while test $# -gt 0; do
	case $1 in
	-all)
		flag=1
		;;
	*)
		args+=("$1")
		;;
	esac
	shift
done

count=0
counter()
{
	r=$(echo $1 | grep -o "[0-9]\+ ")
	if [ -n "$r" ]
	then
		count=$((count + r))
	fi
}

out()
{
	exec 3>&1
	counter "$($global -d "${args[@]}" 2>&1 1>&3)"
	counter "$($global -r "${args[@]}" 2>&1 1>&3)"
	counter "$($global -s "${args[@]}" 2>&1 1>&3)"
	exec 3>&-
	if [ $count -eq 0 ]
	then
		echo object not found
	else
		echo $count objects located
	fi
}

if [ $flag -eq 1 ]
then
	out | sed 's/\t/  /g'
else
	$global "${args[@]}"
fi
