#!/bin/python3

import re 
import subprocess
from tabulate import tabulate

vms = []
for line in subprocess.getoutput("pgrep qemu-system-x86 -a").splitlines():
    vm = []
    
    port=line.split()[0]

    names = re.findall('-name [\w-]+', line)
    if names:
        name = names[0].split()[1]
    else:
        name = "NULL"

    mons = re.findall('-monitor telnet:0.0.0.0:\d+', line)
    if mons:
        mon = mons[0].split(":")[2]
    else:
        mon = -1

    nets = []
    blks = []
    tcps = re.findall('-monitor tcp:0.0.0.0:\d+', line)
    if tcps:
        tcp = tcps[0].split(":")[2]

        i = 0
        for netstr in subprocess.getoutput("echo info network |nc -N 127.0.0.1 " + tcp + " | grep -v ^\(qemu\) | grep -v \"^QEMU \"").splitlines():
            if (i % 2) == 0:
                net = []
                net.append(netstr.split(":")[0])
                nets.append(net)
            else:
                nets[-1].append(re.findall("ifname=tap\d+", netstr)[0].split("=")[1])
            i = i + 1

        for blk in subprocess.getoutput("echo info block |nc -N 127.0.0.1 " + tcp + " | grep -v ^\(qemu\) | grep -v \"^QEMU \" | sed '1i\\\\' | sed 's/\r//g' | sed -n '/^$/{n;p;}' | grep -o '/[^ \"]*'").splitlines():
            blks.append(blk)

    else:
        tcp = -1

    vncs = re.findall('-vnc :\d+', line)
    if vncs:
        vnc = int(vncs[0].split(":")[1]) + 5900
    else:
        vnc = -1

    spis = re.findall('-spice port=\d+', line)
    if spis:
        spi = spis[0].split("=")[1]
    else:
        spi = -1

    vm.append(port)
    vm.append(name)
    vm.append(vnc)
    vm.append(spi)
    vm.append(mon)
    vm.append(tcp)
    vm.append(nets)
    vm.append(blks)

    vms.append(vm)

print(tabulate(vms, headers=["pid", "name" ,"vnc", "spi", "mon", "tcp", "nets", "blks"]))
