#!/bin/bash

br=nat-br
net=192.168.53.1/24

if [ ! -e /sys/class/net/$br/bridge ] ; then
  ip link add name $br type bridge
  ip addr add $net dev $br
  ip link set $br up
  iptables -t nat -I POSTROUTING -s $net -j MASQUERADE
  echo 1 > /proc/sys/net/ipv4/ip_forward
fi

ip link set $1 master $br
ip link set $1 up
