#!/bin/sh

BRIDGE=br0
NETWORK=192.168.53.0
NETMASK=255.255.255.0
GATEWAY=192.168.53.1
DHCPRANGE=192.168.53.2,192.168.53.254

echo 1 > /proc/sys/net/ipv4/ip_forward

if [[ -z $(ip a | grep -E "^[0-9]+" | awk '{print $2}' | tr -d ':' | grep ^"$BRIDGE"$) ]] ; then
  ip link add name $BRIDGE type bridge
  ip addr add $GATEWAY/$NETMASK dev $BRIDGE
  ip link set $BRIDGE up
  
iptables-restore <<EOF
*nat
-A POSTROUTING -s $NETWORK/$NETMASK -j MASQUERADE 
COMMIT
*filter
-A FORWARD -i $1 -o $1 -j ACCEPT 
-A FORWARD -s $NETWORK/$NETMASK -i $BRIDGE -j ACCEPT 
-A FORWARD -d $NETWORK/$NETMASK -o $BRIDGE -m state --state RELATED,ESTABLISHED -j ACCEPT 
COMMIT
EOF

  dnsmasq --interface=$BRIDGE --strict-order --except-interface=lo --listen-address=$GATEWAY --bind-interfaces --dhcp-range=$DHCPRANGE --dhcp-no-override

fi

ip link set $1 master $BRIDGE
ip link set $1 up
