#!/bin/bash

net=nat
printf -v mac_addr "52:54:%02x:%02x:%02x:%02x" $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff )) $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff ))

args=("$@")
for ((i=$(("${#args[@]}" - 1)); i>=0; --i)); do
  case ${args[i]} in
  -mac)
    mac_addr=${args[i+1]}
    unset args[i]
    unset args[i+1]
    ;;
  -br)
    net=bridge
    unset args[i]
    ;;
  -vnc)
    if [[ ${args[i+1]} != :* ]]; then
      vnc=" -vnc :"$(($(comm -3 <(seq 5900 6000) <(ss -nltp | grep "\"qemu-system-x86\"" | awk '{print $4}' | grep -Eo "[0-9]+$" | sort -V | uniq) | head -n 1) - 5900))
      unset args[i]
    fi
    ;;
  esac
done

tap_number=$(comm -3 <(seq -f "%02g" 0 99) <(ip a | grep -Eo "^[0-9]+: tap[0-9]+" | awk '{gsub("tap","", $2); printf "%02d\n", $2}' | sort -V) | head -n 1 | sed -E 's/^0{1}//')

qemu-system-x86_64 -enable-kvm \
  -chardev pty,id=c0 -device isa-serial,chardev=c0 \
  -netdev tap,id=tap0,ifname=tap"$tap_number",script=/etc/qemu-ifup-$net,downscript=/etc/qemu-ifdown-$net \
  -device e1000,netdev=tap0,mac=$mac_addr \
  $vnc "${args[@]}"
