#!/bin/sh

BRIDGE=br1

IP=$(ip a | grep $ETHERNET | grep " inet " | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b/[0-9]+ ")
[[ $(echo $IP) =~ " " ]] && echo There are multiple ip, Unable to process && exit 1

GATEWAY=$(ip route | grep $ETHERNET | grep "default via" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
[[ $(echo $GATEWAY) =~ " " ]] && echo There are multiple default route, Unable to process && exit 2

if [[ -z $(ip a | grep -E "^[0-9]+" | awk '{print $2}' | tr -d ':' | grep ^"$BRIDGE"$) ]] ; then
  ip link add $BRIDGE type bridge
  ip link set $ETHERNET master $BRIDGE
  ip link set $BRIDGE up
  ip addr del $IP dev $ETHERNET
  ip addr add $IP dev $BRIDGE
  ip route add default via $GATEWAY
fi

ip link set $1 master $BRIDGE
ip link set $1 up
