#!/bin/sh

BRIDGE=br1
ETHERNET=eno1
IP=$(ip a | grep $ETHERNET | grep " inet " | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b/[0-9]+ " | tail -n 1)
GATEWAY=$(ip route | grep $ETHERNET | grep "default via" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")

if [[ -z $(bridge -d link | awk '{print $2}' | grep ^"$BRIDGE":$) ]] ; then
  ip link add $BRIDGE type bridge
  ip link set $ETHERNET master $BRIDGE
  ip link set $BRIDGE up
  ip addr del $IP dev $ETHERNET
  ip addr add $IP dev $BRIDGE
  ip route add default via $GATEWAY
fi

ip link set $1 master $BRIDGE
ip link set $1 up
