#!/bin/bash

PROGNAME="$(basename $0)"
usage() {
  echo "Usage: "$PROGNAME" <disk path> [options]"
  echo
  echo "Options:"
  echo "  -h or -help     display this help and exit"
  echo "  -br             Set the network mode to bridge (default is nat)"
  echo "  -vnc            Enable vnc and assign ports in order"
  echo "  -mac            Set mac address"
  echo
  echo "Examples:"
  echo "  "$PROGNAME" fedora.qcow2"
  echo "  "$PROGNAME" fedora.qcow2 -vnc :0"
  echo "  "$PROGNAME" fedora.qcow2 -vnc -br -mac 52:54:91:2c:1e:8d"
  echo "  "$PROGNAME" fedora.qcow2 -kernel /mnt/c/linux/arch/x86_64/boot/bzImage -append \"root=/dev/vda1 console=ttyS0\""
}

if [[ -z $1 ]] || [[ $1 = "-h" ]] || [[ $1 = "-help" ]]; then
  usage
  exit 0
fi
[[ ! -f $1 ]] && echo \<$1\> not is a file && exit 1

disk=" -drive file=$1,if=virtio "
smp=" -smp 6 "
mem=" -m 4g "
net=nat
vnc=""
mac_addr=""
tap_number=$(comm -3 <(seq -f "%02g" 0 99) <(ip a | grep -Eo "^[0-9]+: tap[0-9]+" | awk '{gsub("tap","", $2); printf "%02d\n", $2}' | sort -V) | head -n 1 | sed -E 's/^0{1}//')
export ETHERNET=""

mkdir -p /var/run/qemu-wrapper/
mac_history=/var/run/qemu-wrapper/mac_address_history
[[ -f $mac_history ]] && mac_addr=$(grep "^$1 " $mac_history | awk '{print $2}')
if [[ -z $mac_addr ]]; then
  printf -v mac_addr '52:54:%02x:%02x:%02x:%02x' $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff )) $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff ))
  echo $1 $mac_addr >> $mac_history
fi

args=("$@")
for ((i=$(("${#args[@]}" - 1)); i > 0; --i)); do
  case ${args[i]} in
  -smp)
    smp=""
    ;;
  -m)
    mem=""
    ;;
  -mac)
    mac_addr=${args[i+1]}
    unset args[i]
    unset args[i+1]
    ;;
  -br)
    ETHERNET=${args[i+1]}
    net=bridge
    unset args[i]
    unset args[i+1]
    ;;
  -vnc)
    if [[ ${args[i+1]} != :* ]]; then
      vnc=" -vnc :"$(($(comm -3 <(seq 5900 6000) <(ss -nltp | grep "\"qemu-system-x86\"" | awk '{print $4}' | grep -Eo "[0-9]+$" | sort -V | uniq) | head -n 1) - 5900))
      unset args[i]
    fi
    ;;
  esac
done
unset args[0]
echo mac address : $mac_addr

qemu-system-x86_64 -enable-kvm -cpu host \
  -chardev pty,id=c0 -device isa-serial,chardev=c0 \
  -netdev tap,id=tap0,ifname=tap$tap_number,script=/etc/qemu-ifup-$net,downscript=/etc/qemu-ifdown-$net \
  -device virtio-net,netdev=tap0,mac=$mac_addr \
  -device virtio-rng-pci \
  $disk $smp $mem $vnc "${args[@]}"
