#!/bin/bash

ip link set $1 nomaster

if is_bridge_interface $NAT_BRIDGE && [[ -z $(ip link show master $NAT_BRIDGE) ]] ; then
  ip link del $NAT_BRIDGE
  pkill -9 -f "^dnsmasq --interface=$NAT_BRIDGE "
  iptables -t nat -D PREROUTING -i $NAT_BRIDGE -p tcp --dport 53 -j DNAT --to-destination $NAT_GATEWAY:5353
  iptables -t nat -D PREROUTING -i $NAT_BRIDGE -p udp --dport 53 -j DNAT --to-destination $NAT_GATEWAY:5353
  iptables -t nat -D POSTROUTING -s $NAT_NETWORK/$NAT_NETMASK -j MASQUERADE
  iptables -D FORWARD -s $NAT_NETWORK/$NAT_NETMASK -i $NAT_BRIDGE -j ACCEPT
  iptables -D FORWARD -d $NAT_NETWORK/$NAT_NETMASK -o $NAT_BRIDGE -m state --state RELATED,ESTABLISHED -j ACCEPT
  iptables -D INPUT -i $NAT_BRIDGE -p tcp --dport $NAT_DNS_PORT -j ACCEPT
  iptables -D INPUT -i $NAT_BRIDGE -p udp --dport $NAT_DNS_PORT -j ACCEPT
  iptables -D INPUT -i $NAT_BRIDGE -p udp --dport 67 -j ACCEPT
fi
