#!/bin/python3

import re 
import subprocess
from tabulate import tabulate

vms = []
index = 0
for line in subprocess.getoutput("pgrep qemu-system- -a").splitlines():
	vm = []
	
	port=line.split()[0]

	names = re.findall('-name [\\w-]+', line)
	if names:
		name = names[0].split()[1]
	else:
		name = "NULL"

	vncs = re.findall('-vnc :\\d+', line)
	if vncs:
		vnc = vncs[0].split(":")[1]
	else:
		vnc = -1

	spis = re.findall('-spice port=\\d+', line)
	if spis:
		spi = spis[0].split("=")[1]
	else:
		spi = -1
	
	mons = re.findall('-serial mon:telnet:0.0.0.0:\\d+', line)
	if mons:
		mon = mons[0].split(":")[3]
	else:
		mon = -1

	vm.append(index)
	vm.append(port)
	vm.append(name)
	vm.append(vnc)
	vm.append(spi)
	vm.append(mon)

	vms.append(vm)
	index = index +1

head = []
head.append("index")
head.append("pid")
head.append("name")
head.append("vnc")
head.append("spi")
head.append("mon")

print(tabulate(vms, head))
