#!/bin/bash

echo 1 > /proc/sys/net/ipv4/ip_forward

if ! is_bridge_interface $NAT_BRIDGE; then
  ip link add name $NAT_BRIDGE type bridge
  ip addr add $NAT_GATEWAY/$NAT_NETMASK dev $NAT_BRIDGE
  ip link set $NAT_BRIDGE up
  
  iptables -t nat -I POSTROUTING -s $NAT_NETWORK/$NAT_NETMASK -j MASQUERADE
fi

ip link set $1 master $NAT_BRIDGE
ip link set $1 up
