#!/bin/bash

smp="-smp 4,sockets=1,cores=4"
mem="-m 4g"
export nettype=bridge
printf -v mac '52:54:%02x:%02x:%02x:%02x' $(($RANDOM & 0xff)) $(($RANDOM & 0xff)) $(($RANDOM & 0xff)) $(($RANDOM & 0xff))
export eth=enp5s0
args=()

mkdir -p /var/run/qemu-wrapper/
mac_history=/var/run/qemu-wrapper/mac_address
touch $mac_history

while test $# -gt 0; do
  case $1 in
  -name)
    mac_addr=$(grep "$2" $mac_history | cut -d "=" -f 2)
    if [ -z "$mac_addr" ]; then
      echo "$2"="$mac" >> $mac_history
    else
      mac="$mac_addr"
    fi
    args+=("$1")
    ;;
  -smp)
    smp=""
    args+=("$1")
    ;;
  -m)
    mem=""
    args+=("$1")
    ;;
  -eth)
    eth="$2"
    shift
    ;;
  -br)
    nettype=bridge
    ;;
  -nat)
    nettype=nat
    ;;
  -rvd)
    args+=("-drive file=$2,format=raw,if=virtio")
    shift
    ;;
  -rsd)
    args+=("-drive file=$2,format=raw")
    shift
    ;;
  -qvd)
    args+=("-drive file=$2,format=qcow2,if=virtio")
    shift
    ;;
  -spi)
    args+=("-vga qxl -spice port=$2,addr=0.0.0.0,disable-ticketing -device virtio-serial-pci,id=virtio-serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,chardev=charchannel0,name=com.redhat.spice.0 -device qemu-xhci,id=usb -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,bus=usb.0,port=1 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,bus=usb.0,port=2")
    usb=",usb=off"
    shift
    ;;
  *)
    args+=("$1")
    ;;
  esac
  shift
done

qemu-system-x86_64 ${args[@]} $smp $mem -machine q35,accel=kvm"$usb" -cpu host -rtc base=localtime -netdev tap,id=tap0 -device virtio-net-pci,netdev=tap0,mac="$mac" -monitor telnet:0.0.0.0:0,server,nowait

