#!/bin/bash

export https_proxy=http://192.168.1.2:7890

key=/usr/local/share/trans/key
val=/usr/local/share/trans/value
touch $key $val

trans_word="trans -no-ansi -show-prompt-message N -show-languages N -show-original-phonetics N -show-translation-phonetics N -show-alternatives N -s en :zh"
trans_line="trans -no-ansi -show-prompt-message N -s en :zh -b"

if [ -z "$1" ]; then
	str="$(xsel -o)"
else
	str="$1"
fi
str=$(echo -n "$str" | sed 's/^\s*\*\s*//')
str=$(echo -n "$str" | sed 's/^\s*#*\s*//')
str=$(echo -n "$str" | sed 's/^\s*\/\/\s*//')
str=$(echo -n "$str" | sed 's/^>*//')
str=$(echo -n "$str" | sed 's/^\s*;;//')
str=$(echo -n "$str" | perl -0pe 's/(‐|-)\s*\n\s*//g')
str=$(echo -n "$str" | tr '\n' ' '| sed 's/\t\+/ /g' | sed 's/ \+/ /g' | sed 's/^ //' | sed 's/ $//')

echo "$str" | grep -x "\[*[$\"(*“”]*[a-zA-Z]\+[\".,;:)”?/!]*\]*" > /dev/null
if [ $? -eq 0 ]; then
	str=${str//[$\".,;*:()“”?\/\[\]!]/}
else
	echo "$str"
	echo
fi

num=$(grep -niFx -- "$str" $key | cut -f1 -d: | head -1)
if [ -z $num ]; then
	echo "$str" | grep "^[a-zA-Z]\+$" > /dev/null
	if [ $? -eq 0 ]; then
		ret=$($trans_word "$str" 2> /dev/null)
	else
		ret=$($trans_line "$str" 2> /dev/null)
	fi
	if [ $? -eq 0 ]; then
		echo "$str" >> $key
		echo "$ret" | tr '\n' '\0' >> $val
		echo >> $val
	fi
else
	ret=$(sed -n ${num}p $val | tr '\0' '\n')
fi

echo "$ret" | sed 's/u003d/=/g' | head -n 40
read
